version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "8080:8080"

  database:
    container_name: database
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app-db
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - "12345:3306"
    command: ["mysqld", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci", "--bind-address=0.0.0.0"]
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
