{
 "title": "Appjet Server METRICS",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Grafana & Influx Containers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Graph",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "query": "from(bucket: \"my_bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"container_metrics\")\n  |> filter(fn: (r) => r[\"container_name\"] == \"grafana-influx-grafana-1\" or r[\"container_name\"] == \"grafana-influx-influxdb-1\")\n  |> filter(fn: (r) => r[\"_field\"] == \"cpu\")\n  |> map(fn: (r) => ({ r with _value: r._value * 100.0 }))\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n  |> yield(name: \"mean\")\n"
      }
     ]
    },
    {
     "title": "Memory Graph",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "targets": [
      {
       "query": "from(bucket: \"my_bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"container_metrics\")\n  |> filter(fn: (r) => r[\"container_name\"] == \"grafana-influx-grafana-1\" or r[\"container_name\"] == \"grafana-influx-influxdb-1\")\n  |> filter(fn: (r) => r[\"_field\"] == \"memory\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n  |> yield(name: \"mean\")\n\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Appjet Server Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Server Http Requests Cumulative Count",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "query": "from(bucket: \"my_bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_requests\")\n  |> filter(fn: (r) => r[\"metric\"] == \"http_request_count\")\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: true)\n  |> cumulativeSum(columns: [\"_value\"])\n  |> yield(name: \"cumulative_sum\")\n"
      }
     ]
    },
    {
     "title": "CPU & Memory Appjet Server Graph",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"my_bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"container_metrics\")\n  |> filter(fn: (r) => r[\"container_name\"] == \"scripts-app_name_xpto-1\")\n  |> filter(fn: (r) => r[\"_field\"] == \"cpu\" or r[\"_field\"] == \"memory\")\n  |> map(fn: (r) => ({ r with _value: r._value }))\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n  |> yield(name: \"mean\")\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Logging",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Appjet Server logs",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3 },
     "targets": [
      {
       "query": "from(bucket: \"my_bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"application_logs\")\n  |> filter(fn: (r) => r[\"level\"] == \"info\")\n  |> keep(columns: [\"_time\", \"level\", \"_value\"])  // Keep only the columns you want\n  |> rename(columns: {_time: \"Time\", level: \"Level\", _value: \"Log Message\"})  // Rename columns for clarity\n  |> yield(name: \"logs\")\n"
      }
     ]
    }
   ]
  }
 ]
}